config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # resources :alerts, only: %i[index]
  # resources :sessions, only: %i[new create]
  # get "/logout", to: "sessions#destroy"
  # root "alerts#index"

  get '/login', to: 'sessions#new', as: 'login'
  post '/auth/ldap', to: 'sessions#create', as: 'new_session' # Comment when SSO!
  get '/auth/:provider/callback', to: 'sessions#create'
  post '/auth/:provider/callback', to: 'sessions#create' # remove after https://github.com/omniauth/omniauth/pull/1106
  get '/auth/failure', to: 'sessions#failure'
  post '/logout', to: 'sessions#destroy', as: 'logout'

  resources :alerts, only: %i[index show update] do
    collection do
      patch :bulk_action # bulk_action_alert_path
    end
  end

  resources :lifetimes, only: %i[index new create destroy]
  resources :audit_logs, only: %i[index]

  # get '/login', to: 'sessions#new', as: 'login'
  # post '/login', to: 'sessions#create', as: 'new_session'
  # post '/logout', to: 'sessions#destroy', as: 'logout'

  get '/auth/openid_connect/callback', to: 'sso_sessions#create'
  get '/auth/failure', to: 'sso_sessions#failure'

  get '/about', to: 'pages#about', as: 'about'

  namespace :api do
    namespace :v1 do
      post '/alerts', to: 'alerts#create'
      post '/arrange_alerts', to: 'alerts#arrange_alerts'
      resources :ip_addresses, only: [:index, :create, :update, :destroy]
      resources :domain_names, only: [:index, :create, :update, :destroy]
    end
  end

  resources :ip_addresses, only: %i[index]
  resources :domain_names, only: %i[index]

  root "alerts#index"
end

app/views/shared/_flash.html.erb
<%= turbo_frame_tag 'notice' do %>
  <div id="notice" data-controller="flash" class="absolute bottom-0 right-0 max-w-lg mx-auto mr-8 flash-msg">
    <% flash.each do |key, value| %>
      <% if key == 'errors' %>
        <% value.each do |error| %>
          <div class="flex bg-red-100 rounded-lg p-4 mb-4 text-sm text-red-700">
            <svg class="w-5 h-5 inline mr-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
            <div> <span class="font-medium">Error!</span> <%= error %></div>
          </div>
        <% end %>
      <% elsif key == 'success' %>
        <div class="flex bg-green-100 rounded-lg p-4 mb-4 text-sm text-green-700">
          <svg class="w-5 h-5 inline mr-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
          <div> <span class="font-medium">Success!</span> <%= value %></div>
        </div>
      <% elsif key == 'warning' %>
        <div class="flex bg-yellow-100 rounded-lg p-4 mb-4 text-sm text-yellow-700">
          <svg class="w-5 h-5 inline mr-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
          <div> <span class="font-medium"></span> <%= value %></div>
        </div>
      <% elsif key == 'info' %>
        <div class="flex bg-blue-100 rounded-lg p-4 mb-4 text-sm text-blue-700">
          <svg class="w-5 h-5 inline mr-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
          <div> <span class="font-medium">Info!</span> <%= value %></div>
        </div>
      <% end %>
    <% end %>
  </div>
 <% end %>

app/views/shared/_form_errors.html.erb
<% if object.errors.any? %>
  <div class="bg-pink-100 rounded-lg p-4 md:px-6 mb-4 text-pink-700 text-sm">
    <h2 class="font-semibold mb-3">The form contains <%= pluralize(object.errors.count, "error") %></h2>

    <ul class="list-inside list-disc">
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="flex flex-wrap items-center justify-between py-2 text-gray-700 container mx-auto">
  <!--div class="flex items-center mr-6 flex-no-shrink">
    <%= link_to "/", class:"link text-xl tracking-tight font-black" do %>
      <span class="sr-only">Add your app name here</span>
      <%# Remove this logo and add your own %>
      <svg fill="none" class="w-9 h-9" height="512" viewBox="0 0 512 512" width="512" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><linearGradient id="a" gradientUnits="userSpaceOnUse" x1="56" x2="463" y1="46" y2="465"><stop offset="0" stop-color="#8038ed"/><stop offset="1" stop-color="#3a0092"/></linearGradient><path d="m0 0h512v512h-512z" fill="#fff"/><rect fill="url(#a)" height="512" rx="110" width="512"/><g stroke="#fff"><circle cx="190" cy="302" r="79.5" stroke-opacity=".9" stroke-width="25"/><circle cx="254" cy="377" r="34" stroke-opacity=".8" stroke-width="10"/><circle cx="282" cy="227" r="106" stroke-width="50"/></g></svg>
    <% end %>
  </div-->
  <div class="block lg:hidden">
    <%# Mobile nav toggle %>
    <button class="flex items-center p-2 -mr-1 rounded-lg focus:bg-gray-100" data-action="click->nav#toggleMenu touch->nav#toggleMenu">
      <svg class="stroke-current text-gray-500 w-7 h-7" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><title>Menu</title><g fill="none"><path d="M4 6h16M4 12h8m-8 6h16" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path></g></svg>
    </button>
  </div>
  <div class="items-center w-full text-center lg:flex-1 lg:flex lg:text-left pt-2 lg:pt-0 hidden" data-nav-target="menu">
    <div class="lg:flex-grow">
    <%= link_to alerts_path, data: { turbo_frame: :main, turbo_action: 'replace' } do %>
      <i class="fa-solid fa-bars p-3 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block"></i>
    <% end %>
      <%# <i class="fa-solid fa-bars"></i> %>
      <!--%= link_to "Alerts", "#", class: "p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" %-->
      
    </div>
    <!--%= Time.zone.now %-->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
            
    <div class="items-center block w-full mt-2 text-center lg:flex lg:flex-row lg:flex-1 lg:mt-0 lg:text-left lg:justify-end">
      <div><%# More links can go here %></div>
      <%= link_to about_path, data: { turbo_frame: :main, turbo_action: 'replace' } do %>
        <i class="fa-solid fa-question"></i>
      <% end %>

      <span class="h-5 w-px bg-gray-200 mx-3"></span>

      <%= link_to logout_path, data: { turbo_method: :post } do %>
        <i class="fa-solid fa-arrow-right-from-bracket"></i>
      <% end %>
    </div>
  </div>
</nav>