config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # resources :alerts, only: %i[index]
  # resources :sessions, only: %i[new create]
  # get "/logout", to: "sessions#destroy"
  # root "alerts#index"

  get '/login', to: 'sessions#new', as: 'login'
  post '/auth/ldap', to: 'sessions#create', as: 'new_session' # Comment when SSO!
  get '/auth/:provider/callback', to: 'sessions#create'
  post '/auth/:provider/callback', to: 'sessions#create' # remove after https://github.com/omniauth/omniauth/pull/1106
  get '/auth/failure', to: 'sessions#failure'
  post '/logout', to: 'sessions#destroy', as: 'logout'

  resources :alerts, only: %i[index show update] do
    collection do
      patch :bulk_action # bulk_action_alert_path
    end
  end

  resources :lifetimes, only: %i[index new create destroy]
  resources :audit_logs, only: %i[index]

  # get '/login', to: 'sessions#new', as: 'login'
  # post '/login', to: 'sessions#create', as: 'new_session'
  # post '/logout', to: 'sessions#destroy', as: 'logout'

  get '/auth/openid_connect/callback', to: 'sso_sessions#create'
  get '/auth/failure', to: 'sso_sessions#failure'

  get '/about', to: 'pages#about', as: 'about'

  namespace :api do
    namespace :v1 do
      post '/alerts', to: 'alerts#create'
      post '/arrange_alerts', to: 'alerts#arrange_alerts'
      resources :ip_addresses, only: [:index, :create, :update, :destroy]
      resources :domain_names, only: [:index, :create, :update, :destroy]
    end
  end

  resources :ip_addresses, only: %i[index]
  resources :domain_names, only: %i[index]

  root "alerts#index"
end

app/models/alert.rb
require 'csv'

class Alert < ApplicationRecord
  belongs_to :assignee, class_name: 'alert', foreign_key: :assignee_id, optional: true

  validates :source, presence: true

  ALERT_ORDERED = ['Critical', 'High', 'Medium', 'Low']

  def self.order_by_case
    ret = "CASE"
    ALERT_ORDERED.each_with_index do |p, i|
      ret << " WHEN severity = '#{p}' THEN #{i}"
    end
    ret << " END ASC"
  end

  scope :by_severity, -> { order(Arel.sql(order_by_case)) }

  def self.get_csv(alerts)
    CSV.generate do |csv|
      csv << ["Title", "Assets"]

      alerts.each do |alert|
        csv << [alert.title, alert.asset]
      end
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    ["asset", "source", "title", "hide_responded", "history_mode"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end

  # this ransacker is created to make "Hide alerts containing issue" working. Do not remove!
  ransacker :hide_responded, formatter: proc { |v| v == true } do |parent|
    # Arel.sql("alerts.issue IS NOT NULL AND alerts.issue != ''")
  end

  # this ransacker is created to make "Switch to history mode" working. Do not remove!
  ransacker :history_mode, formatter: proc { |v| v == false } do |parent|
    # pass
  end

end

app/models/user.rb
# require 'auth_ldap'
class User < ApplicationRecord
  has_many :alerts, foreign_key: :assignee_id

  # def self.authenticate(username, password)
  #   username = username.downcase
  #   user = User.find_by(username: username)
  #   if user
  #     auth_ldap = AuthLDAP.new # (LDAP_CONFIG)

  #     if auth_ldap.authenticate(username, password) == true
  #       user
  #     else
  #       false
  #     end
  #   else
  #     false
  #   end
  # end
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :authorize
  before_action :set_alert, only: %i[show edit update]
  before_action :set_mode, only: %i[index]
  
  def index
    search_params = params.permit(:format, :page, q: [:title_or_asset_or_source_cont, :s, :hide_responded, :history_mode])
    # @q = Alert.where(active: true).ransack(search_params[:q])

    # Determine if the checkbox is checked
    if params[:q] && params[:q][:hide_responded] == 'true'
      # Checkbox is checked, filter for alerts with a non-empty issue field
      @q = Alert.where(active: @active, issue: ['', nil]).ransack(search_params[:q])
    else
      # Checkbox is unchecked, filter for alerts with an empty issue field
      @q = Alert.where(active: @active).ransack(search_params[:q])
    end

    alerts = @q.result.by_severity.order(created_at: :desc)
    @pagy, @alerts = pagy_countless(alerts, items: 50)
  end

  def show
  end

  def bulk_action
    @selected_alerts = Alert.where(id: params.fetch(:alert_ids, []).compact)

    if @selected_alerts.empty?
      # TODO: flash with error
      return
    end

    if params[:button] == 'close'
      @selected_alerts.update_all(active: :false, last_closed_at: Time.now, last_closed_by: current_user.displayname)
      @selected_alerts.each do |alert|
        AuditLog.create(
          alert_id: alert.id,
          event_description: "Alert {title: #{alert.title}, asset: #{alert.asset}} has been closed by #{current_user.displayname}"
        )
      end
    elsif params[:button] == 'open'
      @selected_alerts.update_all(active: :true, updated_at: Time.now)
      @selected_alerts.each do |alert|
        AuditLog.create(
          alert_id: alert.id,
          event_description: "Alert {title: #{alert.title}, asset: #{alert.asset}} has been re-opened by #{current_user.displayname}"
        )
      end
    # for other buttons, elsif should be added right here. Issue should be in the "end"
    elsif params[:button] == 'csv'
      csv = Alert.get_csv(@selected_alerts)
      send_data csv, :type => 'text/csv; charset=utf-8; header=present', :disposition => 'attachment; filename=alerts.csv'
      return
    else
      @selected_alerts.update_all(issue: params[:issue])
    end

    redirect_to action: :index
  end


  # # PATCH/PUT /alerts/1 or /alerts/1.json
  # def update
  #   # respond_to do |format|
  #   #   if @alert.update(alert_params)
  #   #     format.turbo_stream { render turbo_stream: turbo_stream.replace(@alert, partial: "alerts/alert", locals: {alert: @alert}) }
  #   #     format.html { redirect_to alert_url(@alert), notice: "Alert was successfully updated." }
  #   #     format.json { render :show, status: :ok, location: @alert }
  #   #   else
  #   #     format.html { render :edit, status: :unprocessable_entity }
  #   #     format.json { render json: @alert.errors, status: :unprocessable_entity }
  #   #   end
  #   # end
  # end


  private

  def set_alert
    @alert = Alert.find(params[:id])
  end

  def set_mode
    @active = params[:q]&.[](:history_mode) || true
  end

  def alert_params
    params.require(:alert).permit(:title, :asset)
  end

end

app/controllers/api/v1/alerts_controller.rb
class Api::V1::AlertsController < ApplicationController
  before_action :auth_from_token
  skip_before_action :verify_authenticity_token
  before_action :generate_uuid, only: [:create]
  before_action :set_alert, only: [:create]

  # POST /api/v1/alerts
  def create
    if @alert
      handle_alert
    else
      create_alert
    end
  end

  # POST /api/v1/arrange_alerts
  def arrange_alerts
    # Close all outdated or resolved alerts assotiated to watcher 
    # Expect json containing watcher name and currently active alerts IDs.
    # {
    #   source: "dummy-watcher",
    #   current_alerts: [ "id-1", "id-2", "id-n" ]
    # }
    close_resolved_alerts
  end

  private

  def generate_uuid
    title = alert_params[:title] || ''
    asset = alert_params[:asset] || ''
    @uuid = Digest::UUID.uuid_v3(Digest::UUID::DNS_NAMESPACE, title + asset)
  end

  def set_alert
    @alert = Alert.find_by(id: @uuid)
  end

  def alert_params
    params.permit(:title, :asset, :severity, :remediation, :active, :source, :issue,
                  :output, :nessus_plugin_id, :dc, cve_list: [])
  end

  def handle_alert
    if @alert.active && alert_params[:active] == 'false'
      close_alert
      AuditLog.create(
        alert_id: @alert.id,
        event_description: "Alert {title: #{@alert.title}, asset: #{@alert.asset}} has been closed by #{@alert.source}"
      )
    elsif !@alert.active && alert_params[:active] == 'true'
      reopen_alert
      AuditLog.create(
        alert_id: @alert.id,
        event_description: "Alert {title: #{@alert.title}, asset: #{@alert.asset}} has been re-opened by #{@alert.source}"
      )
    else
      update_alert
    end
  end

  def close_alert
    update_alert_attributes(last_closed_at: Time.now, last_closed_by: 'bot', active: false)
  end

  def reopen_alert
    update_alert_attributes(alert_params.merge(last_detected_at: Time.now, active: true, resurfaced: true))
    SlackNotificationService.notify_reopened_alert(@alert)
  end

  def update_alert
    update_alert_attributes(alert_params.merge(last_detected_at: Time.now, active: true))
  end

  def update_alert_attributes(attributes)
    if @alert.update(attributes)
      render json: { data: @alert }
    else
      render json: @alert.errors, status: :unprocessable_entity
    end
  end

  def create_alert
    @alert = Alert.new(alert_params.merge(id: @uuid, last_detected_at: Time.now))
    if @alert.save
      AuditLog.create(
        alert_id: @alert.id,
        event_description: "Alert {title: #{@alert.title}, asset: #{@alert.asset}} has been created by #{@alert.source}"
      )
      SlackNotificationService.notify_new_alert(@alert)
      render json: { data: @alert }, status: :created
    else
      render json: @alert.errors, status: :unprocessable_entity
    end
  end

  def close_resolved_alerts
    return unless params[:source].present?

    all_active_alerts = Alert.where(source: params[:source], active: true).ids
    resolved_alerts_ids = all_active_alerts - params[:current_alerts]

    return unless resolved_alerts_ids.any?
  
    resolved_alerts = Alert.where(id: resolved_alerts_ids)

    resolved_alerts.each do |alert|
      AuditLog.create(
        alert_id: alert.id,
        event_description: "Alert {title: #{alert.title}, asset: #{alert.asset}} has been closed by #{alert.source}"
      )
    end

    if Alert.where(id: resolved_alerts).update_all(
         last_closed_at: Time.now,
         last_closed_by: 'bot',
         active: false
       )
      head :ok
    end
  end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/views/alerts/_alert.html.erb
<tr id="<%= dom_id(alert) %>" class="border-b border-gray-200 hover:bg-gray-100">
  <td class="px-5 text-left whitespace-nowrap hidden md:table-cell">
    <% if alert.severity == 'Critical' %>
      <span class="text-red-600 px-1 rounded-full text-xs font-semibold"><%= alert.severity %></span>
    <% elsif alert.severity == 'High' %>
      <span class="text-orange-600 px-1 rounded-full text-xs font-semibold"><%= alert.severity %></span>
    <% elsif alert.severity == 'Medium' %>
      <span class="text-yellow-600 px-1 rounded-full text-xs font-semibold"><%= alert.severity %></span>
    <% elsif alert.severity == 'Low' %>
      <span class="text-green-600 px-1 rounded-full text-xs font-semibold"><%= alert.severity %></span>
    <% end %>
  </td>
  <td class="px-3 text-left py-2">
    <div class="flex items-center break-all">
      <%# <div class="mr-2">
        <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
              width="24" height="24"
              viewBox="0 0 48 48"
              style=" fill:#000000;">
          <path fill="#80deea" d="M24,34C11.1,34,1,29.6,1,24c0-5.6,10.1-10,23-10c12.9,0,23,4.4,23,10C47,29.6,36.9,34,24,34z M24,16	c-12.6,0-21,4.1-21,8c0,3.9,8.4,8,21,8s21-4.1,21-8C45,20.1,36.6,16,24,16z"></path><path fill="#80deea" d="M15.1,44.6c-1,0-1.8-0.2-2.6-0.7C7.6,41.1,8.9,30.2,15.3,19l0,0c3-5.2,6.7-9.6,10.3-12.4c3.9-3,7.4-3.9,9.8-2.5	c2.5,1.4,3.4,4.9,2.8,9.8c-0.6,4.6-2.6,10-5.6,15.2c-3,5.2-6.7,9.6-10.3,12.4C19.7,43.5,17.2,44.6,15.1,44.6z M32.9,5.4	c-1.6,0-3.7,0.9-6,2.7c-3.4,2.7-6.9,6.9-9.8,11.9l0,0c-6.3,10.9-6.9,20.3-3.6,22.2c1.7,1,4.5,0.1,7.6-2.3c3.4-2.7,6.9-6.9,9.8-11.9	c2.9-5,4.8-10.1,5.4-14.4c0.5-4-0.1-6.8-1.8-7.8C34,5.6,33.5,5.4,32.9,5.4z"></path><path fill="#80deea" d="M33,44.6c-5,0-12.2-6.1-17.6-15.6C8.9,17.8,7.6,6.9,12.5,4.1l0,0C17.4,1.3,26.2,7.8,32.7,19	c3,5.2,5,10.6,5.6,15.2c0.7,4.9-0.3,8.3-2.8,9.8C34.7,44.4,33.9,44.6,33,44.6z M13.5,5.8c-3.3,1.9-2.7,11.3,3.6,22.2	c6.3,10.9,14.1,16.1,17.4,14.2c1.7-1,2.3-3.8,1.8-7.8c-0.6-4.3-2.5-9.4-5.4-14.4C24.6,9.1,16.8,3.9,13.5,5.8L13.5,5.8z"></path><circle cx="24" cy="24" r="4" fill="#80deea"></circle>
        </svg>
      </div> %>
      <%= link_to alert_path(alert), data: { turbo_frame: :main } do %>
      <p class="text-xs font-semibold text-gray-600">
        <%= alert.title %>
        <% if alert.resurfaced %> 
          <span class="ml-3 bg-blue-50 text-blue-300 text-xs font-light mr-2 px-2.5 rounded-lg">Resurfaced</span>
        <% end %>
      </p>
      <% end %>
    </div>
  </td>

  <td class="px-4 text-left">
    <div class="flex text-xs font-medium text-gray-500 break-all">
      <span><%= alert.asset %></span>
    </div>
  </td>

  <td class="px-4 text-left hidden md:table-cell">
    <div class="flex text-xs font-medium text-gray-500 break-all">
      <span><%= alert.source%></span>
    </div>
  </td>

  <td class="px-4 text-center hidden md:table-cell">
    <div class="flex w-full text-xs font-medium text-gray-500 break-all">
      <% if alert.issue.to_s.match?(URI::DEFAULT_PARSER.make_regexp) %>
        <div class="mr-1">
          <i class="fa fa-link text-blue-600"></i>
        </div>
        <a href="<%= alert.issue %>">Reference</a>
      <% elsif alert.issue.present? %>
        <div class="mr-1">
          <i class="fa-regular fa-comments"></i>
        </div>
        <span><%= alert.issue %></span>
      <% end %>
    </div>
  </td>

  <!--td class="py-1 px-6 text-center">
    <div class="flex items-center justify-center">
      <img class="w-6 h-6 rounded-full border-gray-200 border transform hover:scale-125" src="https://randomuser.me/api/portraits/men/1.jpg"/>
      <%# <img class="w-6 h-6 rounded-full border-gray-200 border -m-1 transform hover:scale-125" src="https://randomuser.me/api/portraits/women/2.jpg"/> %>
    </div>
  </td-->

  <td class="px-6 text-center hidden md:table-cell">
    <div class="flex item-center justify-center">
      <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
        <div id="<%= dom_id alert %>">
            <%= check_box_tag "alert_ids[]",
                                alert.id,
                                nil,
                                {
                                data: { 
                                  checkbox_select_all_target: "child", 
                                  action: "change->checkbox-select-all#toggleParent change->checkbox-select-all#toggleActions" 
                                },
                                multiple: true,
                                form: :bulk_actions_form,
                                checked: false, class: "bg-gray-100 border-gray-300 rounded"
                                } %>
        </div>
        <%# <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
        </svg> %>
      </div>
      <%# <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
          </svg>
      </div> %>
    </div>
  </td>
</tr>

app/views/alerts/index.html.erb
<%= turbo_frame_tag :main, data: { turbo_action: 'advance' } do %>
  <!--%= render "shared/index_filter" %-->
  <div data-controller="checkbox-select-all" class="bg-white shadow-md rounded mt-3">
    <div class="bg-gray-100 p-1 shadow-lg">
      <div class="flex flex-row scrollbar-hide">

          <div class="p-1 lg:w-2/3">
            <%= search_form_for @q, data: { turbo_frame: :results } do |f| %>
              <div class="flex space-x-4 items-center"> <!-- Add a container for the checkbox and label -->
                <%= f.search_field :title_or_asset_or_source_cont,
                                    placeholder: "Filter",
                                    oninput: 'this.form.requestSubmit()',
                                    autofocus: true,
                                    autocomplete: 'off',
                                    class: "flex rounded-md border border-gray-200 px-3 py-1 lg:w-1/2 bg-white" %>
                
                <label class="hidden md:flex items-center">
                  <%= f.check_box :hide_responded, {class: "bg-gray-100 border-gray-300 rounded", oninput: 'this.form.requestSubmit()'}, true, false %>
                    <div class="ml-2 flex text-xs font-medium text-gray-500">
                      <span>Hide alerts containing issue</span>
                    </div>
                </label>

                <label class="hidden md:flex items-center">
                <%= f.check_box :history_mode, {class: "bg-gray-100 border-gray-300 rounded", oninput: 'this.form.requestSubmit()'}, false, false %>
                  <div class="ml-2 flex text-xs font-medium text-gray-500">
                    <span>Switch to history mode</span>
                  </div>
                </label>

              </div>
            <% end %>
          </div>

        <div class="basis-1/2 justify-end flex p-1">
          <div data-checkbox-select-all-target="actions" class="hidden">
            <div class="hidden md:block">
              <%= form_with(url: bulk_action_alerts_path, id: :bulk_actions_form, method: :patch, data: { turbo: "false" }, class: "flex space-x-2 py-1") do |f| %>
                <%= f.button type: "submit", value: :csv do %>
                  <i class="fa-solid fa-file-csv text-slate-600 px-1"></i>
                <% end %>
                <%= f.button type: "submit", value: :close do %>
                    <i class="fa-regular fa-trash-can text-slate-700 px-1"></i>
                <% end %>
                <%= f.button type: "submit", value: :open do %>
                    <i class="fa-solid fa-trash-arrow-up text-slate-700 px-1"></i>
                <% end %>
                <%= f.text_field :issue, placeholder: "comment or link", class: "px-3 py-1 text-xs rounded-l-md border border-gray-200 w-full bg-white relative left-3" %>
                <%= f.button type: "submit", class: "px-3 bg-slate-500 text-white text-xs leading-tight rounded-r-md shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition" do %>
                    <i class="fa-solid fa-feather-pointed"></i>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="max-h-[calc(100vh-4rem)] overflow-y-auto">
    <%= turbo_frame_tag :results, data: { turbo_action: 'advance' } do %>
      <div class="bg-white shadow overflow-hidden sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead>
            <tr class="bg-gray-50 text-gray text-sm leading-3">
              <th class="py-3 px-2 text-left md:w-24 hidden md:table-cell">Severity</th>
              <th class="py-3 px-3 text-left"><%= sort_link @q, :title, "Title", {}, { data: { turbo_frame: :results} } %></th>
              <th class="py-3 px-4 text-left md:w-64"><%= sort_link @q, :asset, "Asset", {}, { data: { turbo_frame: :results} } %></th>
              <th class="py-3 px-4 text-left md:w-52 hidden md:table-cell"><%= sort_link @q, :source, "Source", {}, { data: { turbo_frame: :results} } %></th>
              <th class="py-3 px-4 text-left md:w-52 hidden md:table-cell"><%= sort_link @q, :issue, "Issue", {}, { data: { turbo_frame: :results} } %></th>
              <th class="py-3 px-6 content-end w-16 hidden md:table-cell">
                  <%= check_box_tag "select all", 
                                    nil, 
                                    nil, 
                                    {
                                    data: { 
                                      checkbox_select_all_target: "parent", 
                                      action: "change->checkbox-select-all#toggleChildren change->checkbox-select-all#toggleActions" }, 
                                    class: "bg-gray-100 border-gray-300 rounded" 
                                    } %>
              </th>
            </tr>
          </thead>
          <tbody id="alerts" class="text-gray-600 text-sm font-light">

          </tbody>
        </table>
      </div>
    <%= turbo_frame_tag :pagination, loading: :lazy,  data: { turbo_action: 'advance' },
                        src: alerts_path(format: :turbo_stream, q: params[:q]&.to_unsafe_h) %>
    <% end %>
     </div>
  </div>
<% end %>

app/views/alerts/index.turbo_stream.erb
<%= turbo_stream.append :alerts do %>
  <% @alerts.each do |alert| %>
      <%= render "alert", alert: alert %>
  <% end %>
<% end %>

<% if @pagy.next.present? %>
  <%= turbo_stream.replace :pagination do %>
    <%= turbo_frame_tag :pagination, 
                        loading: :lazy,
                        src: alerts_path(format: :turbo_stream, page: @pagy.next, q: params[:q]&.to_unsafe_h) %>
  <% end %>
<% end %>

app/views/alerts/show.html.erb
<div id="<%= dom_id(@alert) %>">
  <%= turbo_frame_tag :main, data: { turbo_action: 'advance' } do %>

<div class='flex justify-center'>  <div class="rounded-xl border p-5 shadow-md w-9/12 bg-white">
    <div class="flex w-full items-center justify-between border-b pb-3">
      <div class="flex items-center space-x-3">
      <i class="h-4 w-4 rounded-full fa-solid fa-feather"></i>
        <div class="text-lg font-bold text-slate-700">Alert details</div>
      </div>
      <div class="flex items-center space-x-8">
        <%= link_to '/alerts', class: "text-lg text-neutral-800" do %>
        <i class="fa-regular fa-circle-xmark"></i>
        <% end %>
      </div>
    </div>

    <div class="mt-4 mb-6">
      <div class="mb-3 text-xl font-bold break-all"><%= @alert.title %></div>
      <% if @alert.output.present? %>
        <div class="bg-gray-50 rounded-lg shadow-inner p-4">
          <div class="text-sm text-neutral-600">
            <% begin %>
              <div class="overflow-x-auto whitespace-nowrap">
                <%= @alert.output.gsub("\r\n", "\n").gsub(/(\s*\n){3,}/, "\n\n").gsub("\n", "<br>").gsub(" ", "&nbsp;").html_safe %>
              </div>
            <% rescue %>
              <%= @alert.output %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>


<div class="mt-4 mb-6">
  <div class="flex flex-col space-y-2">

    <div class="flex flex-wrap items-start text-sm font-bold">
      <div class="w-full sm:w-1/4">Asset</div>
      <div class="w-full sm:w-3/4 text-neutral-600 break-all"><%= @alert.asset %></div>
    </div>

    <div class="flex flex-wrap items-start text-sm font-bold">
      <div class="w-full sm:w-1/4">Remediation</div>
      <div class="w-full sm:w-3/4 text-neutral-600 break-all"><%= @alert.remediation %></div>
    </div>

    <div class="flex flex-wrap items-start text-sm font-bold">
      <div class="w-full sm:w-1/4">Source</div>
      <div class="text-neutral-600 break-all flex-1"><%= @alert.source %></div>
    </div>

    <div class="flex flex-wrap items-start text-sm font-bold">
      <div class="w-full sm:w-1/4">Severity</div>
      <div class="w-full sm:w-3/4 text-neutral-600 break-all"><%= @alert.severity %></div>
    </div>

    <div class="flex flex-wrap items-start text-sm font-bold">
      <div class="w-full sm:w-1/4">Issue</div>
      <div class="w-full sm:w-3/4 text-neutral-600"><%= @alert.issue.to_s.gsub(/\[.*?\]/,'') %></div>
    </div>
    
    <div class="flex flex-wrap items-start text-sm font-bold">
      <div class="w-full sm:w-1/4">CVE list</div>
      <div class="w-full sm:w-3/4 text-neutral-600"><%= @alert.cve_list.join(', ') %></div>
    </div>

    <div class="flex flex-wrap items-start text-sm font-bold">
      <div class="w-full sm:w-1/4">DC/Network</div>
      <div class="w-full sm:w-3/4 text-neutral-600"><%= @alert.dc %></div>
    </div>

    <div class="flex flex-wrap items-start text-sm font-bold">
      <div class="w-full sm:w-1/4">Vulnerability details</div>
      <div class="w-full sm:w-3/4 text-neutral-600"><%= @alert.nessus_plugin_id %></div>
    </div>

    <div class="flex flex-wrap items-start text-sm font-bold">
      <div class="w-full sm:w-1/4">Created at</div>
      <div class="w-full sm:w-3/4 text-neutral-600"><%= @alert.created_at %></div>
    </div>

    <div class="flex flex-wrap items-start text-sm font-bold">
      <div class="w-full sm:w-1/4">Last detected at</div>
      <div class="w-full sm:w-3/4 text-neutral-600"><%= @alert.last_detected_at %></div>
    </div>

    <div class="flex flex-wrap items-start text-sm font-bold">
      <div class="w-full sm:w-1/4">Last closed at</div>
      <div class="w-full sm:w-3/4 text-neutral-600"><%= @alert.last_closed_at %></div>
    </div>

    <div class="flex flex-wrap items-start text-sm font-bold">
      <div class="w-full sm:w-1/4">Last closed by</div>
      <div class="w-full sm:w-3/4 text-neutral-600"><%= @alert.last_closed_by %></div>
    </div>

    <div class="flex flex-wrap items-start text-sm font-bold">
      <div class="w-full sm:w-1/4">Active</div>
      <div class="w-full sm:w-3/4 text-neutral-600"><%= @alert.active %></div>
    </div>

  </div>
</div>

    <%# <div>
      <div class="flex items-center justify-between text-slate-500">
        <div class="flex space-x-4 md:space-x-8">
          <div class="flex cursor-pointer items-center transition hover:text-slate-600">
            <svg xmlns="http://www.w3.org/2000/svg" class="mr-1.5 h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z" />
            </svg>
            <span>125</span>
          </div>
        </div>
      </div>
    </div> %>
  </div>
</div>


<% end %>
</div>