config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # resources :alerts, only: %i[index]
  # resources :sessions, only: %i[new create]
  # get "/logout", to: "sessions#destroy"
  # root "alerts#index"

  get '/login', to: 'sessions#new', as: 'login'
  post '/auth/ldap', to: 'sessions#create', as: 'new_session' # Comment when SSO!
  get '/auth/:provider/callback', to: 'sessions#create'
  post '/auth/:provider/callback', to: 'sessions#create' # remove after https://github.com/omniauth/omniauth/pull/1106
  get '/auth/failure', to: 'sessions#failure'
  post '/logout', to: 'sessions#destroy', as: 'logout'

  resources :alerts, only: %i[index show update] do
    collection do
      patch :bulk_action # bulk_action_alert_path
    end
  end

  resources :lifetimes, only: %i[index new create destroy]
  resources :audit_logs, only: %i[index]

  # get '/login', to: 'sessions#new', as: 'login'
  # post '/login', to: 'sessions#create', as: 'new_session'
  # post '/logout', to: 'sessions#destroy', as: 'logout'

  get '/auth/openid_connect/callback', to: 'sso_sessions#create'
  get '/auth/failure', to: 'sso_sessions#failure'

  get '/about', to: 'pages#about', as: 'about'

  namespace :api do
    namespace :v1 do
      post '/alerts', to: 'alerts#create'
      post '/arrange_alerts', to: 'alerts#arrange_alerts'
      resources :ip_addresses, only: [:index, :create, :update, :destroy]
      resources :domain_names, only: [:index, :create, :update, :destroy]
    end
  end

  resources :ip_addresses, only: %i[index]
  resources :domain_names, only: %i[index]

  root "alerts#index"
end

app/models/lifetime.rb
class Lifetime < ApplicationRecord
  validates :source, presence: true, uniqueness: true
  validates :alert_lifetime_days, presence: true, numericality: { only_integer: true, greater_than: 0 }

end

app/controllers/lifetimes_controller.rb
class LifetimesController < ApplicationController
  before_action :authorize
  before_action :set_lifetime, only: %i[destroy]
  
  def index
    @lifetimes = Lifetime.all
  end

  def new
    @lifetime = Lifetime.new
  end

  def create
    @lifetime = Lifetime.new(lifetime_params)
    if @lifetime.save
      flash[:success] = "Created"
      redirect_to lifetimes_path
    else
      flash[:errors] = @lifetime.errors.full_messages
      redirect_to lifetimes_path
    end
  end

  def destroy
    if @lifetime.destroy
      flash[:success] = "Deleted"
      redirect_back(fallback_location: lifetimes_path)
    else
      flash[:errors] = @lifetime.errors.full_messages
      redirect_back(fallback_location: lifetimes_path)
    end
  end

  private

  def set_lifetime
    @lifetime = Lifetime.find(params[:id])
  end

  def lifetime_params
    params.require(:lifetime).permit(:source, :alert_lifetime_days)
  end

end

app/views/lifetimes/_form_lifetime.html.erb
<%= turbo_frame_tag :remote_modal_new_lifetime, target: :_top do %>
  <div data-controller="modal" class="hidden fixed inset-0 overflow-y-auto flex items-center justify-center backdrop " style="z-index: 9999;">
    <!-- Modal Card -->
    <div class="m-1 bg-white rounded shadow max-h-screen w-full max-w-lg relative">
      <!-- Close button moved to top right corner -->
      <%= link_to lifetimes_path, data: { action: 'click->modal#close' }, class: 'absolute top-0 right-0 m-4' do %>
        <%= content_tag(:i, "close", class: "fa-solid fa-xmark") %>
      <% end %>
      
      <div class="p-6">
        <%= form_with model: @lifetime, url: lifetimes_path(@lifetime), method: :post, data: {turbo: false} do |form| %>

          <%= form.label :source, class: "block uppercase text-xs font-bold mb-2 required-label" %>
          <%= form.text_field :source, class: "border-1 py-0.5 border-gray-200 rounded focus:ring-1 w-full" %>

          <%= form.label :alert_lifetime_days, class: "block uppercase text-xs font-bold mb-2 mt-3 required-label" %>
          <%= form.text_field :alert_lifetime_days, class: "border-1 py-0.5 border-gray-200 rounded focus:ring-1 w-full" %>

          <div class="flex justify-end mt-6">
            <div class="flex lg:flex-row lg:items-center">
              <%= form.submit "Submit", class: "px-3 py-1 text-xs font-medium text-center text-white bg-blue-700 rounded-sm hover:bg-blue-800 w-20 h-6" %>
            </div>
          </div>
        <% end %> 
      </div>

    </div>
  </div>
<% end %>

app/views/lifetimes/index.html.erb
<div class="container max-w-xl mx-auto px-3 py-8 text-xs">
  <div class="flex items-center sm:items-start sm:flex-row flex-col text-gray-900">
    <div class="flex-grow sm:text-left text-center mt-2 sm:mt-0">
      <h1 class="title-font font-bold text-sm">Lifetime configuration</h1>
      <p class="text-xs">Set alerts expiration (in days) based on its source (watcher)</p>
    </div>
    <div class="flex-grow sm:text-left mt-2 sm:mt-1 justify-end flex">
      <%= link_to "Create lifetime", new_lifetime_path, data: { turbo_frame: :main },  
      class: 'px-2 py-1 text-xs font-medium text-center text-white bg-blue-700 rounded-sm hover:bg-blue-800' %>
    </div>
  </div>
  
  <ul class="py-8">
    <% @lifetimes.each do |lifetime| %>
      <li class="flex border-b border-gray-200 py-1 items-center">
        <div class="w-3/4 px-2">
          <p class="text-xs font-medium truncate">
            <%= lifetime.source %>
          </p>
        </div>
        <div class="w-1/4 px-2">
          <div class="text-xs font-medium truncate inline-flex items-center">
            <%= lifetime.alert_lifetime_days %> day(s) 
            <%= button_to lifetime, method: :delete, data: { turbo: false }, class: "flex items-center text-red-900 px-3" do %>
                <%= content_tag(:i, "close", class: "fa-solid fa-xmark") %>
            <% end %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/lifetimes/new.html.erb
<%= render partial: "lifetimes/form_lifetime" %>

app/views/lifetimes/new.turbo_stream.erb
<%= turbo_stream.replace "remote_modal_new_lifetime" do %>
  <%= render partial: "lifetimes/form_lifetime" %>
<% end %>