config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # resources :alerts, only: %i[index]
  # resources :sessions, only: %i[new create]
  # get "/logout", to: "sessions#destroy"
  # root "alerts#index"

  get '/login', to: 'sessions#new', as: 'login'
  post '/auth/ldap', to: 'sessions#create', as: 'new_session' # Comment when SSO!
  get '/auth/:provider/callback', to: 'sessions#create'
  post '/auth/:provider/callback', to: 'sessions#create' # remove after https://github.com/omniauth/omniauth/pull/1106
  get '/auth/failure', to: 'sessions#failure'
  post '/logout', to: 'sessions#destroy', as: 'logout'

  resources :alerts, only: %i[index show update] do
    collection do
      patch :bulk_action # bulk_action_alert_path
    end
  end

  resources :lifetimes, only: %i[index new create destroy]
  resources :audit_logs, only: %i[index]

  # get '/login', to: 'sessions#new', as: 'login'
  # post '/login', to: 'sessions#create', as: 'new_session'
  # post '/logout', to: 'sessions#destroy', as: 'logout'

  get '/auth/openid_connect/callback', to: 'sso_sessions#create'
  get '/auth/failure', to: 'sso_sessions#failure'

  get '/about', to: 'pages#about', as: 'about'

  namespace :api do
    namespace :v1 do
      post '/alerts', to: 'alerts#create'
      post '/arrange_alerts', to: 'alerts#arrange_alerts'
      resources :ip_addresses, only: [:index, :create, :update, :destroy]
      resources :domain_names, only: [:index, :create, :update, :destroy]
    end
  end

  resources :ip_addresses, only: %i[index]
  resources :domain_names, only: %i[index]

  root "alerts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>ASAP</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div data-controller="reveal" data-reveal-hidden-class="-translate-x-full" class="h-full w-full flex flex-col">
      <header class="w-full bg-white border-b border-gray-200 py-1 relative z-50">
        <div class="px-3 py-1">
          <div class="flex items-center justify-between">
            <div class="flex items-center justify-start">
              <button data-action="click->reveal#toggle" type="button" class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 mr-4">
                <i class="material-icons">menu_open</i>
              </button>
              <a href="https://<%= ENV['HOSTNAME'] %>" class="flex">
                <% app_name = 'ASAP' %>
                <% if app_name %>
                  <%= content_tag(:span, app_name, class: "text-2xl font-bold") %>
                <% else %>
                  <%= image_tag "logo.svg", alt: "", class: "w-22 h-8 mr-3" %>
                <% end %>
              </a>
            </div>
            <div class="flex items-center text-sm">
              <%= button_to logout_path, method: :post, data: {turbo: false}, class: "flex items-center text-gray-900" do %>
                <div class="inline-flex items-center">
                  <i class="material-icons">logout</i>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </header>

      <div class="flex flex-1 relative">
        <aside data-reveal-target="item" class="fixed top-0 left-0 z-40 w-64 h-screen pt-16 transition-transform -translate-x-full border-r bg-white">
          <div class="h-full px-3 pb-4 overflow-y-auto">
            <ul class="space-y-1 font-medium">
              <li>
                <%= link_to root_path, class: ["flex items-center p-2 text-gray-900 rounded-lg hover:bg-gray-100", ("bg-gray-100" if request.path == root_path)] do %>
                  <%= content_tag(:i, "gpp_maybe", class: "material-icons") %>
                  <%= content_tag(:span, "Alerts", class: "flex-1 ml-3 whitespace-nowrap") %>
                <% end %>
              </li>

              <li>
                <%= link_to lifetimes_path, class: ["flex items-center p-2 text-gray-900 rounded-lg hover:bg-gray-100", ("bg-gray-100" if request.path == lifetimes_path)] do %>
                  <%= content_tag(:i, "timer", class: "material-icons") %>
                  <%= content_tag(:span, "Lifetimes", class: "flex-1 ml-3 whitespace-nowrap") %>
                <% end %>
              </li>

              <li>
                <%= link_to audit_logs_path, class: ["flex items-center p-2 text-gray-900 rounded-lg hover:bg-gray-100", ("bg-gray-100" if request.path == audit_logs_path)] do %>
                  <%= content_tag(:i, "manage_search", class: "material-icons") %>
                  <%= content_tag(:span, "Audit logs", class: "flex-1 ml-3 whitespace-nowrap") %>
                <% end %>
              </li>

              <li>
                <%= link_to ip_addresses_path, class: ["flex items-center p-2 text-gray-900 rounded-lg hover:bg-gray-100", ("bg-gray-100" if request.path == audit_logs_path)] do %>
                  <%= content_tag(:i, "dns", class: "material-icons") %>
                  <%= content_tag(:span, "IP Addresses", class: "flex-1 ml-3 whitespace-nowrap") %>
                <% end %>
              </li>

              <li>
                <%= link_to domain_names_path, class: ["flex items-center p-2 text-gray-900 rounded-lg hover:bg-gray-100", ("bg-gray-100" if request.path == audit_logs_path)] do %>
                  <%= content_tag(:i, "dns", class: "material-icons") %>
                  <%= content_tag(:span, "Domain names", class: "flex-1 ml-3 whitespace-nowrap") %>
                <% end %>
              </li>
            </ul>
          </div>
        </aside>

        <main class="flex-1 overflow-auto">
          <div class="w-full h-full p-4">
            <%= render partial: "shared/flash" %>
            <%= yield %>
            <%= turbo_frame_tag "remote_modal" %>
          </div>
        </main>
      </div>
    </div>

  </body>

</html>

<style>
/* remove if https://github.com/tailwindlabs/tailwindcss/pull/5732 gets released */
/* Hide scrollbar */
body::-webkit-scrollbar{
  display: none; /* Chrome, Safari and Opera */
}
html, body {
  -ms-overflow-style: none;  /* IE and Edge */
  scrollbar-width: none;  /* Firefox */
}
</style>

app/views/layouts/errors.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title><%= Rails.application.class.module_parent_name %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ASAP</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="min-w-screen min-h-screen bg-gray-100 flex items-center justify-center overflow-hidden">
    <div class="rounded">
        <!--%= render partial: 'shared/flash', flash: flash %-->
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </div>
    </div>
  </body>
</html>